### ISSUE TITLE
Work on Login_Layout Backend

### ISSUE THREAD

**Issue by HealthTeam17** [HealthTeam17/Record-Health#18]
Create a centralized database and Authenticate on login activity
Start: 22 Nov
End: 23 Nov

**Comment by Detective-Khalifah** [comment]
I do not get the _centralized database_ part.
Could we use Firebase Authenticate for login?

**Comment by Detective-Khalifah** [comment]
Are we using Firebase's Cloud Firestore or Realtime database or some other database management system (DBMS)?
Is there a schema?

**Comment by HealthTeam17** [comment]
@Detective-Khalifah Which one is much convenient and time friendly? You can use as you prefer

**Comment by Detective-Khalifah** [comment]
_A centralized database (sometimes abbreviated CDB) is a database that is located, stored, and maintained in a single location. This location is most often a central computer or database system, for example a desktop or server CPU, or a mainframe computer._ - Wikipedia
That's why I'm asking if we're using Firebase.
I could quickly set up an SQLite dB using Room, considering the time constraint and lack of a schema I could reference.
